name: Sync Labels from Central Config
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Runs on a schedule (daily at 2 AM UTC)
  schedule:
    - cron: '0 2 * * *'
  # Also runs when changes are pushed to the default branch,
  # specifically if the central config file path is mentioned.
  push:
    branches: [ main, master ]

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the central .github repository into a specific folder
      - name: Checkout central config repo
        uses: actions/checkout@v4
        with:
          repository: ForYouPage-Org/.github
          path: .github-central # This is a temporary folder name

      # Step 2: Run the label syncer using the local file from the checkout
      - name: Sync Labels
        uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github-central/labels.yml # Point to the file in the temp folder
          prune: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
